# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sequel_plus}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Lang"]
  s.date = %q{2011-05-13}
  s.description = %q{Provides plugins and extensions for Sequel}
  s.email = %q{mwlang@cybrains.net}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "lib/extensions/export.rb",
    "lib/sequel_plus.rb",
    "lib/sequel_tree.rb",
    "lib/tasks/sequel.rake",
    "lib/tasks/sequel.rb",
    "test/helper.rb",
    "test/test_export.rb",
    "test/test_sequel_tree.rb"
  ]
  s.homepage = %q{http://github.com/mwlang/sequel_plus}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{provides plugins and extensions for Sequel}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bacon>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<sequel>, [">= 3.0.0"])
    else
      s.add_dependency(%q<bacon>, [">= 1.0.0"])
      s.add_dependency(%q<sequel>, [">= 3.0.0"])
    end
  else
    s.add_dependency(%q<bacon>, [">= 1.0.0"])
    s.add_dependency(%q<sequel>, [">= 3.0.0"])
  end
end

